### PR TITLE
Remove temporary file

### PR DESCRIPTION
**Pull request by snoozer05**

### CODE REVIEW

**Comment by amatsuda** [comment]
I don't really like adding any editor specific configuration to the `.gitignore` file in shared projects (although I'm also a Vimmer).
Should we add `*.sw?`,  `*~`, `*.sublime-workspace`, `.project`, `.idea`, etcetc. to every project on GH? That is silly :dizzy_face:

**Comment by indirect** [comment]
I agree with this—if it's your editor, you should exclude the files in your user gitignore, not in a shared project.

**Comment by snoozer05** [comment]
I understand.  @amatsuda thanks for your comment.
@indirect I'm sorry for wrong fix. I make PR to fix it soon.  Please merge if there is no problem.

**Comment by snoozer05** [comment]
oo. I notice it already reverted. thank you.

**Pull request merged**
