### PR TITLE
added rails source annotation support

### PR DESCRIPTION
**Pull request by jparker**
Would you be opposed to adding support for Rails' source annotations to get `rake notes` to process HAML files?

### CODE REVIEW

**Comment by indirect** [comment]
Uh... I don't even know what Rails source annotations are! Could you explain? :)

**Comment by jparker** [comment]
Certainly!

But first, definitely don't merge this. I just took a closer look, and realized, as written, it only works on Rails >= 4.2.0. :flushed: 

The railties gem provides a handful of rake tasks (notes, notes:todo, notes:fixme, etc.) that comb the application for comments of the form /(TODO|FIXME|OPTIMIZE): .*/ and displays them as a list:

    $ cat app/models/foo.rb
    class Foo < ActiveRecord::Base
      # TODO: climb a tree
    end
    $ cat app/views/foos/show.html.erb
    <% # TODO: learn a foreign language %>
    $ rake notes
    app/models/foo.rb:
      * [2] [TODO] climb a tree

    app/views/foos/show.html.erb
      * [1] [TODO] learn a foreign language

The behavior is implemented by SourceAnnotationExtractor::Annotation (https://github.com/rails/rails/blob/4-2-stable/railties/lib/rails/source_annotation_extractor.rb).

After researching it a bit more, it looks like haml is supported in 3-2-stable, 4-0-stable, and 4-1-stable, but this was dropped in 4-2-stable when SourceAnnotationExtractor was refactored.

This PR would provide the behavior, but it will break for Rails <= 4.1. If you think it's sensible for haml-rails to provide this, I can update the PR to work with earlier versions.

**Comment by indirect** [comment]
Ah, I see what you're saying. Sure, I'm happy to add support to haml-rails for this in Rails 4.2+.

**Comment by indirect** [comment]
:ship: released as 0.7.0!

**Pull request merged**
