### PR TITLE
Only the latest Ruby + Rails versions

### PR DESCRIPTION
**Pull request by radar**
Removing support for the older versions of Ruby + Rails will lessen maintenance burden of this project. I did it recently for i18n and really helped. A++ can recommend to others.

### CODE REVIEW

**Comment by syguer** [comment]
Absolutely agree!
I did it for other gem too 😄

**Comment by radar** [comment]
Yes, I think we should continue support for JRuby.

**Comment by radar** [comment]
I am not sure what is up with the JRuby build here. I do not see the same issues on i18n. I will need to investigate later.

**Comment by scones** [comment]
is there a chance this will get merged? i'd hate to reference an unmerged branch/PR in my gemfile for a prolonged time :)

**Comment by amatsuda** [comment]
I guess, keeping the jruby builds always green may not be this project's scope.
jruby on Rails' CI is not always working healthily, and so in fact jruby has been treated as an "allow failure" platform there in the rails repo since almost 3.years.ago https://github.com/rails/rails/commit/ea628f72c3f6ef77752794356fcb358858fd8827

If that's the only reason we're not merging this PR, I'm :+1: to merge this as it is.

**Comment by radar** [comment]
Okay, going ahead and merging this PR.

**Comment by radar** [comment]
Version 2 of this gem has been released and has this patch.

**Comment by amatsuda** [comment]
FYI I just succeeded in making the CI :green_heart: again! https://github.com/indirect/haml-rails/commit/46a94f25693ed6f00386659293c0d1372261a7bd
https://travis-ci.org/indirect/haml-rails/builds/498558176

**Pull request merged**
