### PR TITLE
Update test suite with Rails 5 and more Rubies

### PR DESCRIPTION
**Pull request by JuanitoFatas**
- Update Appraisals file
- Update .travis.yml
  - Add sudo false (container-based, faster)
    
    https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
  - Test more rubies
  - Test newer things on top
  - Exclude Ruby < 2.2 with Rails 5

### CODE REVIEW

**Comment by syguer** [comment]
@indirect why not merged is this?

**Comment by inntran** [comment]
@syguer looks like it breaks a few tests with Rails 4.0, Rails 4.2 on MRI 1.9.3 and JRuby.

**Comment by syguer** [comment]
Thanks reply :)
umm... it really fails caused by this change?
The patch seems to has added configure for Rails 5, not touch to Rails 4.x.
Can anyone rebuild this branch to CI?

**Comment by indirect** [comment]
restarted the build

**Comment by syguer** [comment]
@indirect Thanks for build!
rbx build is failing on my forked repo too. I think it seems travis issue.
I suggest that move rbx to `allow_failures`. But it might not be this PR concern, so I'll fix it as another PR.
How do you think?

**Comment by indirect** [comment]
I am ok with removing rbx from Travis 👍

**Comment by syguer** [comment]
@JuanitoFatas Please remove rbx from travis.yml

**Comment by indirect** [comment]
@syguer since it seems like @JuanitoFatas has moved on, perhaps you could open a new PR based on this one, with those changes?

**Comment by syguer** [comment]
@indirect done! https://github.com/indirect/haml-rails/pull/127

**Pull request closed without merging**
