### PR TITLE
Mailer generator now creates mailer layouts and both html/text templates

### PR DESCRIPTION
**Pull request by mfung**

### CODE REVIEW

**Comment by indirect** [comment]
I don't think it makes sense to use haml for the text layout -- won't that produce html inside the text email?

**Comment by mfung** [comment]
No, the tags are dictated by the templates. the files that are generated for mailers are now in html.haml and text.haml for both html and text emails. This just generates both formats. This also adds the 

app/views/layout/mailer.html.haml and app/views/layout/mailer.txt.haml layouts which it did not before.

text emails are still just text when parsed through because I didn't use any html tags inside the templates. Html emails

**Comment by mfung** [comment]
I am using Rails 4.2 and when I run 'rails generate mailer Notify foo bar' haml-rails was only generating these views:
app/views/notify/foo.text.haml
app/views/notify/bar.text.haml

What I have been doing is 'rails generate mailer notify foo bar -e erb' and then converting each view back to haml. This generates
app/views/layouts/mailer.text.erb
app/views/layouts/mailer.html.erb
app/views/notify/foo.text.erb
app/views/notify/foo.html.erb
app/views/notify/bar.text.erb
app/views/notify/bar.html.erb

Instead my code when you run 'rails generate mailer notify foo bar' generates:
app/views/layouts/mailer.text.haml
app/views/layouts/mailer.html.haml
app/views/notify/foo.text.haml
app/views/notify/foo.html.haml
app/views/notify/bar.text.haml
app/views/notify/bar.html.haml

**Comment by indirect** [comment]
I see, I didn't realize that Haml could be used to generate plaintext. Thanks for this change!

**Comment by mfung** [comment]
Andre I just realized my code only works for Rails 4.1+ because they changed the method filename_with_extensions

4.1+:
def filename_with_extensions(name, format = self.format)
  [name, format, handler].compact.join(".")
end

4.0:
def filename_with_extensions(name)
  [name, format, handler].compact.join(".")
end

**Comment by indirect** [comment]
Oh, I see. Can you send another PR to support both?

**Pull request merged**
