### PR TITLE
allow Rails 6

### PR DESCRIPTION
**Pull request by fauxparse**
`SourceAnnotationExtractor` was moved under `::Rails` in [0ec23effa74e8e9da6ebb14afbd335bea470ab3e](https://github.com/rails/rails/commit/0ec23effa74e8e9da6ebb14afbd335bea470ab3e).

This change looks for the constant in the correct location depending on the Rails version.

### CODE REVIEW

**Comment by radar** [comment]
Thanks very much @fauxparse. I've expanded on this PR over here: https://github.com/fauxparse/haml-rails/pull/1. I think these changes will make haml-rails work correctly with Rails 6.

**Comment by radar** [comment]
Tests appear to be breaking here because Travis has a different Bundler version.

**Comment by indirect** [comment]
you might want to merge in there following PR to get a green build?

@radar I added you to this repo so you can merge this when green

**Comment by fauxparse** [comment]
@indirect Thanks, I'll keep an eye on it -- at the moment CI is still failing on that branch but I'm kind of swamped at work for now anyway.

**Comment by radar** [comment]
I think this is good to merge. I will wait for all the tests to finish running first.

**Comment by radar** [comment]
This was merged in as a part of https://github.com/indirect/haml-rails/pull/150. Thank you!

**Pull request closed without merging**
